### ISSUE TITLE
Layout.ignoresThrowable() seems not to be applied as expected

### ISSUE THREAD

**Issue by messerm** [DECK36/log4javascript#5]
Hi, I'm new into this opensource and I hope this is the right way to address this question/issue.

With 1.4.9 there was code added/moved to the Layout class:
[log4javascript_uncompressed.js#L1027](https://github.com/DECK36/log4javascript/blob/master/log4javascript_uncompressed.js#L1027)

``` javascript
formatWithException: function(loggingEvent) {
            var formatted = this.format(loggingEvent);
            if (loggingEvent.exception && this.ignoresThrowable()) {
                formatted += loggingEvent.getThrowableStrRep();
            }
            return formatted;
        }
```

The flag **ignoresThrowable()** implies to me that the exception should **not** be shown in the logging output. This is also what the documentation implies.
Did I missunderstood the flag or is this a defect?

Regrads
Martyn

**Comment by mikelohmann** [comment]
Please try to ask it in the http://log4javascript.org/ project directly. This project here aims to bring log4javascript to be installable via npm.
