### ISSUE TITLE
batch vs time

### ISSUE THREAD

**Issue by Heshyo** [DECK36/log4javascript#7]
Not sure if it's the right repository to log issues on log4javscript.

Is it possible to send things through AJAX by batch every 10s for ex, no matter how many messages there are to send? I wasn't able to do that so I just hacked the code a bit to support that scenario (but the original batch and or time probably don't work anymore).

**Comment by mikelohmann** [comment]
Please ask it directly in the log4javascript project: http://log4javascript.org/. This project here just aims to bring log4javascript to node via npm.
